"""The operations consumed by the fetch and retention use cases."""
from dataclasses import dataclass
from typing import Protocol

import pandas as pd

from scripts.core.models import SavedArtifacts


class Provider(Protocol):
    def scout(self) -> dict: ...
    def preview(self) -> None: ...
    def extract(self) -> pd.DataFrame: ...
    def preview_transfer_scope(self) -> str: ...
    def needs_full_transfer(self) -> bool: ...
    def population(self) -> int | None: ...
    def release_payload(self) -> None: ...


class Interaction(Protocol):
    def report(self, message: str) -> None: ...
    def consent_to_transfer(self) -> None: ...
    def approve_sample(self, metadata: dict, row_limit: int) -> int: ...
    def show_validation(self, null_ratio: float) -> None: ...


class ArtifactStorage(Protocol):
    def save(self, frame: pd.DataFrame, filename: str) -> SavedArtifacts: ...


@dataclass
class FetchPorts:
    provider: Provider
    interaction: Interaction
    artifacts: ArtifactStorage


class SourceRegistry(Protocol):
    def save(self, name: str, url: str, script: object) -> str: ...
    def defer(self, url: str, script: object) -> str: ...
    def finish(self, token: str, name: str | None) -> str | None: ...
